### ISSUE TITLE
Typo: should be QSFP28 instead of GSFP28

### ISSUE THREAD

**Issue by saunderd-netapp** [NetAppDocs/storagegrid-appliances#16]
### Page URL

https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/cabling-appliance.html

### Page title

Cable appliance

### Summary

SG6100 
step 2
"Connect the two interconnect ports on each storage controller to the 100GbE port on the SG6100-CN controller, using one 100-GbE GSFP28 to 4x25-GbE SFP28 cable."
It should say QSFP28 instead of GSFP28

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Thanks @saunderd-netapp . Typo is now corrected.
