### ISSUE TITLE
Correction on enabling encryption after install

### ISSUE THREAD

**Issue by saunderd-netapp** [NetAppDocs/storagegrid-appliances#19]
### Page URL

https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-enabling-node-encryption.html

### Page title

Optional: Enable node or drive encryption

### Summary

Drive encryption can be enabled after install. Node encryption cannot. "You can also enable node encryption or change your passphrase by placing the appliance in maintenance mode." should be "You can also enable drive encryption or..."

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @saunderd-netapp, thank you for bringing this to our attention. I've opened SGRIDDOC-70 to track this issue.
