### ISSUE TITLE
SG6160 cabling should be deterministic

### ISSUE THREAD

**Issue by mmears** [NetAppDocs/storagegrid-appliances#30]
### Page URL

https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/cabling-appliance.html

### Page title

Cable appliance

### Summary

The SG6060 cabling guide was made deterministic in terms of which FC HBA port should connect to which E2800 controller and port due to feedback from various folks who participate in or oversee StorageGRID appliance installations.  Although all combinations work and are supported, and there is no known technical advantage to one over the another, it's still better to say exactly how to connect the cables, rather than make the users worry about it, and end up with a bunch of different combinations which likely aren't regularly tested.

This learning was not applied to SG6160.

Requesting that the SG6160 cabling guide be updated to specify which pigtail of the breakout cable should be connected to which E4000 controller and port, by referencing the labels on the 25G pigtails.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
@mmears, thank you for bringing this to our attention. I've opened a ticket in SGRIDDOC to track this change and added you as a watcher.
