### ISSUE TITLE
404 link to wrong domain

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/storagegrid-appliances#4]
### Page URL

https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-enabling-node-encryption.html

### Page title

Optional: Enable node or drive encryption

### Summary

There's a link that goes to 
https://review.docs.netapp.com/us-en/storagegrid-118_main/admin/reviewing-storagegrid-encryption-methods.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @scaleoutsean, thanks for highlighting this broken link. I'll get it corrected ASAP.

**Comment by netapp-pcarriga** [comment]
HI @scaleoutsean. These broken links are now corrected. Thanks again for helping us improve our customer documentation.
