### ISSUE TITLE
Dead hyperlink in step 9

### ISSUE THREAD

**Issue by JamieLove-Net2** [NetAppDocs/storagegrid-appliances#8]
### Page URL

https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/replace-cmos-in-sgf6112.html

### Page title

Replace SGF6112 CMOS battery

### Summary

Step 9 that includes a hyperlink to instructions to "enter the drive encryption passphrase" is a dead link and generates a 404 error message.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @JamieLove-Net2, thank you for bringing this issue to our attention. I can confirm that the error has been corrected and link is now working as expected.
